# Generated by Django 3.2.1 on 2021-06-07 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='document',
            field=models.FileField(upload_to='documents'),
        ),
    ]
