# Generated by Django 3.2.1 on 2021-06-14 11:46

import book.models.book
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_book_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pdf',
            field=models.FileField(blank=True, upload_to=book.models.book.upload_pdf_path),
        ),
        migrations.AlterField(
            model_name='book',
            name='document',
            field=models.FileField(blank=True, upload_to=book.models.book.upload_path),
        ),
    ]
